apiVersion: v1
kind: Secret
metadata:
  name: frigate-secret
stringData:
  FRIGATE_MQTT_USERNAME: ENC[AES256_GCM,data:HIjOLrP+vXh7WVjDjcpKjzySX3j+euE6FN4=,iv:cdwVTCAI0L7sSlCXByfNEgCt25STe9H1UhtjV3a9ZvI=,tag:E4649Y3Y0hEeo6ypKMFxUw==,type:str]
  FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:8mG9MmylxhGocDNhkBHSVTpAHFFUg9Y8UiU=,iv:VBNCR0ssYaR/b/C3TJT9ftgJG7ee2QbxhQNMjfCF0PA=,tag:2mo8heplvaWjfNhvkO6SFw==,type:str]
  FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:CVL2vwRyALeZzQ==,iv:mOk7HDpk198tFjehcfNOPyIHIJydW8BnOpwYcm0DFmU=,tag:jJ+Y2p9+Y7vWZLTLWYha4g==,type:str]
  FRIGATE_GENAI_API_KEY: ENC[AES256_GCM,data:Q/uY,iv:86jnbtshyU4Yj93tTUjbfdMOTSqDPLWZ3yVNwPhACxM=,tag:FE4BUhCd+AiSODOINv8koQ==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5akIyTnZ2TmU4ZDJOaWtn
        MS9qb1BvYlIyUlRIQmJTcVVhVnlFNXBUcW00CkVnVStkQUJLM0dIMVE3OTdTOExm
        VCt6L3VneUZrbkdSUnZHNzlMTW9mbVUKLS0tIGVrK2tsZ3FST3lxUzNrR1I2OHVw
        S2RSZ0RMS0gyUDFxOG4waUJDSDdPUnMKSybvaLmxcYFgNTIFHaZFa8cX8VVWdqF3
        0W8ambQTKBJuCeeT/PHgJ7JMRgpMsNnEQ4kAMCDlzd6rWxYGxY9vnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-28T21:39:05Z"
  mac: ENC[AES256_GCM,data:vVnuWnuJFPxI9jlgMzTrq+sZ9kiVDmfETL6DkZMWihgXw9n2TqP/NHzjc9ODv9zsvRmVm9DDMvpZfZOxu6le2si1hLWukQCbfwprRUJeT09cSX/00Nd49HFByvOhgOgD1Og2DlY5shK63h7UQxVd72cBu90SHaZCpTUZLZNbGgc=,iv:wUghADebpE0jfiPoDU7ZcjLsUUC85xPSifEzdbBseJ8=,tag:qSlnbEb8OqJtJeZpAm6b6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
