apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
stringData:
    ALERTMANAGER_API_TOKEN: ENC[AES256_GCM,data:Z8yP6O2yCjizS4/+ZGz4d3gn1uvm3Q+MRQ==,iv:3U6gLZQ9gneUz5pQq6L5oly3YGyBaqO+c30O1fFgjD0=,tag:8Mxwqy6gdsLY7nHz4RD34A==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:3W9lBLlE9tRZ9tgZPCqOndl03oM=,iv:Red3QnahHPpXHcRi7NyeFqv4zMXdvShUP34HGBzAqr4=,tag:zX+wJEb9L6sLD82Y67FxIw==,type:str]
sops:
    age:
        - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXd5NlVYR3NybmZzeCti
            a0VRM0tQM1lzZU92YTBtakJCQmpsN0N5QkdnCmNCd1ZFQ2FqbVBSN003cEp0Y3Fz
            RkhZcVVrWFo4dFA5dlZOT0FJQmJPZDgKLS0tIFhoWHV6RERRdVVEQ0dVcThiYXJR
            UWVaWmhJaGU3NTFnMlFycGtabVVzZFUKQuYVZe8ezlrTO+8x4vpMcBHEnyb4x+XN
            DaFYRHua1rHzAT2h0KPXArle21KueXqtxaxzE56O8pyxiK9XztMMhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T22:25:18Z"
    mac: ENC[AES256_GCM,data:3XmREm0R7Cw2atKc26gHMEGH9vJhOqZ2JTMg5EVKQNCcG2QUsv1/LnLWzxFdmEMXLlg2R+kGijyoS2AiDt+txP60VHRVCBQOp06LP4QlvplXRCSYUpCjimv9/5o2hOizRiMxuLRdNiTbQEcgwDdWkafpdNqJzEKEKM00YYNzw/o=,iv:OwdRVxWS0G9j39zMjgcAslXBIBkDZZNlRJ2ZXnBzqBU=,tag:HYAltyBfdzkQZW996YDwag==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
