---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./media-storage/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./jellyfin/ks.yaml
  - ./flare-bypasser/ks.yaml
  - ./jackett/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./emby/ks.yaml