apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:vA1l8iEDTEaKjh3PacIjBgGXdMzo/g==,iv:570OOCPxOrHYlYtfXjtdVs9UH3QYSZMtKuLr2pWWiFU=,tag:BkbF2mUR0kAo8+AhCjXkiA==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:oANcrqqpyvBVbssaIKK/z3m4E28=,iv:c6vfeg5QxcDFoI2VG07EXXlM0Z0eU4kVhWB8SQJl58I=,tag:bg3VIAI69TFu3h7FHhr01g==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:3WiJonsI2a6//dLax0PubprOpuaWDg==,iv:hiCT+QsoorvUYoW4Kjj3kdQwnz5p6LaMmL2MDdXODl8=,tag:HYQFfBaPyHrkVrsCv4czaw==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:MwQJin+w6t7irx3BFVlYwt9YT36aIg==,iv:KJXOzYV8GF/j0moTqdY58F6kfbtbTGQEMxgpdfd+yF4=,tag:D03iRlrz5C8ylgM42684eA==,type:str]
sops:
    age:
        - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZlVQQ083QW9idVVQc1JJ
            OXQwT0dwbXVRaURqNU1XZGxTdER0ZU5HSEY4ClpxK2ZUTkMrQWs2c0NGNmVvS3pI
            VDQwQnBTTU9FNHFCcFlWNERMS0FlTVkKLS0tIFloWitUK2hnbE1DYzZKUlhwbElh
            aGRVQ3ZvNklzQkdxNWl6V0o0bVlxL1kKagKnr/WGqR5V90Kf2sMGene9wvMNBhPJ
            fzTwWfWEnR7G4AtWttWmQI0PhUFgtT6WDk1JtKfDgYzYxD+8Saq+Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T21:38:36Z"
    mac: ENC[AES256_GCM,data:IAMw0TnOutba6DmxDPI4Rggifc4bcWN9z9rIT8WEJbvB/UhNIx9vV4qnAkMsX5bi5u8A2yWzCSyeZXcofDfbCTv9AHzu7aHSlnwmKRrM4Y94zYc9Mns8AS47x6iwfUiAw2heAIs3pprR4wdqse6BNTxScc829vDbeoNbsvSHM3U=,iv:9lMoiPL2cSiSw74PSjah8T7es58fISFEDXl/J6Br6+o=,tag:cjRNLxkcrMdl67KP/iYmmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
