apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:V5msWPsykAZIFrpMQSXpG4rDzCOm9/+ocCWOn5v97h3E1gdPR2bUPA==,iv:DEnXfzh/c+NlFJhgfdXF6Kwiy0oVlLpqcTfwChULXyw=,tag:cSXc+8DVbZj9WjuNRL1p9w==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQlBPYi9MSXltUlhqd1pj
        T1NyNGpmZzh0dGVmZ3I1dC80akhLeWRKMlJFCmpvRmtOcEh4WDZXMk4ybDdoam96
        ZUlLcGVGd1R6OXh3c1JjeHloR1ZnSkEKLS0tIDRERmdTYkE4ZmxUays4YUh6Sldo
        ZEpSK1gwN0E3c044ODBTVFFSVGk0UHMKx3bauOM3LXl7HxnRbpDy1wvg5xlB0mOn
        Rre7LsNwuL407fuVpWVzMEVglAHl55WKRIGCHnnAWqscnLuPozKdlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T14:30:02Z"
  mac: ENC[AES256_GCM,data:g7XP3WF87HhKD+H6pQZzmaiZnLpQr75NCFNXWXWlinqD0SstfFQSs8GGZM6+O/GoetzMo1crd8CKxPg4VcLvpUCVByXZtwiAymDiwgSemrjE+su8RghE/n3vBDu2q82pHD04sFSPc3HWpa+W/UKD2Y8e0TTwh8TOUsZ4qwXK6uM=,iv:uySQgLApnZNqgeJIIIJ8/nb4u5gTWrCqKOT/BwviQ60=,tag:YjJUAW32h4Do/AcOB0PDPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
