apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:STYhzzweHiEkpsgObY7MSxQT0PntG+huHDDTMWhWb7Z7HnRu2T1byg==,iv:eEKU6YCgjMr80WQ/89H8Qi3zdksGqcJOdlfD+QdW8BM=,tag:vX7wFXCdY0H1XvdAaPiufQ==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVzlOS0VKU09GVVgxY1JF
        Z04veDhKWmJ1b3BELzVUUXRCL0J5MEpWbTJZCnlkT25jV1NOLzNPZVpMK1RaRGNi
        bHRYajkxNmxZU1RQTGxGaUkwY2I5OE0KLS0tIE5rQlBvZDk2NUo4dWVyd2pUVTBL
        cFBxZ3ZsSzRMWENONzZMR2VTaVhvRTAKcq5w6HggEH7Dyw22yCSFARY/kwK0F+X+
        n2YfsokcA3NzAXDbL2OLQc+6F6HRoN2kmLRNgfmrXmJnP6Bdy5FCQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T15:28:13Z"
  mac: ENC[AES256_GCM,data:e4yJ2XqOK8nHg9DppLLxCqg/zi/k+xb4P1Yq8DRfNOYhxoLyKVDQShP3CJVVOXUHX0vcZkTBTfFP0kgkRMA00ktXRTPdpE8owMn+jCwKVXur8+ZzgI39JNlfTWUEBkfNOphF/LM00SUunmNM9XKXVi0IfUoOGtvE64hQKQBQUNI=,iv:yAUNNTEEhCmNlLELhTR2BQkA+IxchOU4eBaSYnzFH2w=,tag:3UcnVM5/+Q7JCM/1SEtShQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
