---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyfin
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin-config-at
  interval: 30m
  values:
    defaultPodOptions:
      runtimeClassName: nvidia
      hostNetwork: true
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 110
              - 993
        containers:
          main:
            image:
              repository: jellyfin/jellyfin
              tag: 10.11.6@sha256:333b647716631443a43c7fabac4b0c46b4e2f036bad19547e00958f10f721b85
            env:
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: all
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: 1G
              JELLYFIN_FFmpeg__analyzeduration: 200M
              TZ: ${TIMEZONE}
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                cpu: 15m
                memory: 1837M
                nvidia.com/gpu: 1
              limits:
                # memory: 15G
                nvidia.com/gpu: 1
    service:
      main:
        controller: main
        annotations:
          io.cilium/lb-ipam-ips: 192.168.108.77
        type: LoadBalancer
        # externalTrafficPolicy: Cluster
        ports:
          http:
            port: &httpPort 8096
          dlna:
            port: 1900
          disco:
            port: 7359

    route:
      app:
        hostnames: ["jelly.${SECRET_DOMAIN}"]
        annotations:
          # external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: jellyfin.png
          gethomepage.dev/name: Jellyfin
          gethomepage.dev/group: Media
          gethomepage.dev/widget.type: jellyfin
          gethomepage.dev/widget.url: http://jellyfin.media.svc.cluster.local:8096
          gethomepage.dev/widget.key: '{{ "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}" }}'
          gatus.home-operations.com/endpoint: |
            conditions:
              - "[STATUS] == 200"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *httpPort

    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
        globalMounts:
          - path: /config
      transcode:
        existingClaim: jellyfin-transcode
        globalMounts:
          - path: /config/cache/transcodes
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 3Gi
        globalMounts:
          - path: /tmp/jellyfin
      media:
        existingClaim: media-storage
        globalMounts:
          - path: /media
      nfs-media:
        type: nfs
        server: tower.local
        path: /mnt/user/media
        globalMounts:
          - path: /nfs-media
            readOnly: false