apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:fjXSjTPkffl3jFI=,iv:kaf5l/YcjTU9JfNy9ErYS27P7YquQstqt9LOT4mPDHg=,tag:ypRSE5dV7ubKBEn/Hbm3VQ==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdFVLUG82dFViTHdDbERF
        WThoVHZIQXF2cnVrSlhENmEwUiswMGxSblI4CnBuNm1RVFRUL3k3Mnk4VnQwbkVq
        OW9wbXh5b01rUkVRc0hodzN1b3BRbmMKLS0tIGh0N1RNcUdKa3RKaXVFRjRUR3Iz
        bWlWZzdkREthN2xsSVljSmM3YjdPb2MKGY1MxXZ30xgOEqlHu166hUxp29lmtPSJ
        e6+2syTJLpVdd8l/S5KDj074V25NyQuo1SiuzcuaC0e82tSWi+OWKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T14:30:02Z"
  mac: ENC[AES256_GCM,data:OJTSnZ7rQWAD4xSlreXZ3kvxejfcNNmsMFJIb6M+w8+3/tHFyjoMo1K54CUE8xNep0msoi9Ysm7JOa+Aj3gc70nVfXh9mJjTQ6mjZ7eJvDnPG9kTei4vqAULN1tj6AbANYA+TncMpcPR3O0ZZzXvrBufPlFk2kwh7AdgckbYysM=,iv:7Y2xPO426Yjge5Fv1UMK1WATp0rn2Iw1Aodh7ok7LzQ=,tag:fxsM4bF5dXCxIIQ281ZzSQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
