apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:jqq0pnLJPawILKU=,iv:jLNHWWcUbLR6XvH3vwWUkbfA1qhn07F18ga+vLbe7qc=,tag:EwGgZgiG9/YbJZhYXzwOtw==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcVFocHhZeUtjSUxUMTV6
        ZVlhTCsreXQ5MkJod204MkJ5YnRFczBuWHlzCkY1SDdDdWdOd3ByRjlOWlI3NmdW
        aXllZy8yejhSOWtGVXNRQkZ3ek4wUDgKLS0tIGJ5UE9WZ2szV1AvY1JkcG9YNzM1
        M1N4bG81MXd2cDdmT3NjQUtBYW56bjgKgdnkL34RxBXyltzQ21HKVmcAo6oLxWLf
        q+b0IyMDHY9PGOD+rOMldCmFLelmrGzZhvMSLqhdDUiDAgEenDliDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T15:28:13Z"
  mac: ENC[AES256_GCM,data:HzT5Z6ogWBUzloBifTuf73lbH5NtUix9EnsdtX0sPdyQhFN9phUCdSFMaSUp7MopBPevW+IGpm5BVjxOfETiK4MuxxBzi0I3OBOthOD6v4MU27s/WaF/z9xWFbVczAmO3vsK3TcwnXeaI0kco30KkEOkmPXdQzcJz/a9fBXfi5Y=,iv:COe5j1RATrBuq4HxS/XS5wl8tlE2rnKuwfFv0WiUiXk=,tag:uHHTjklpQ0QB6RoVzb2xYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
