apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:JtywqrDV/wyp8NK/1evg8JaFQpt3x33lzVkVHsFMPnE=,iv:rvtarEZ723E80Q0oYpDXg+OFREZDKh+ZoQTcRuZVUpA=,tag:11akAXDByoYqGMRPlXYOFA==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZFBWNDlsckJtZHVPaHJx
        Tmg2L2NIaXJDcGlzUFVhZlhqaDllc1hzMmpjCm4yMFQrV0szSG51aXVtRG9lZldV
        cG1aNFRpNk1sRDg2SXJhQ2pTd3lEemMKLS0tIFhOd3pYbTU0L0RnckkvcWdkVUQ5
        bnJTZi9jNzBaM2MzV2EweTVsaWtDN2sKUD/nppnzPhyDQKXbxgDABsVhKIKGhS7/
        sFgFhhlMVQYY84fekpDo8v20N6KwqsuOMCkIwzutCV8tIK1NEnAN8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T15:28:13Z"
  mac: ENC[AES256_GCM,data:MkjSjxTInV0mf47YrFRWJPdDFLOEoNWI38fQxArq9GaF6kqjHQrtZnjHA/WmQlXakmuPWdV8SYQAPgq3K9cxFd7hcvW6qnX3G2V9+vxoCWLoTHeUsJx37MKpwOzcxoPgD5+7fXvtJWGChQ9qNrGbCROA5eT9vumX+QEB/0seRRc=,iv:0TiIfmsCZ0rhtZKD9Q6wCeFk1wj/Hbt5bAWRJlR720U=,tag:9p/q17VabqCIKiL1BPgjVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
