apiVersion: v1
kind: Secret
metadata:
  name: mealie-secret
stringData:
  #ENC[AES256_GCM,data:w7m93adOaohD,iv:dbiwZHTvJPjfLc/R/rKlVyd9zIb5PoeOC60zh3sp8dI=,tag:vxCzHZOiDAbQhONX20dNAA==,type:comment]
  POSTGRES_DB: ENC[AES256_GCM,data:BztvjJb624Y=,iv:8Yc+/4byShZ8oVGZhqo9/qkBFDdUxAmhwKtFuJImHZs=,tag:nbEl9pcZi2zhins6XRaHRw==,type:str]
  POSTGRES_SERVER: ENC[AES256_GCM,data:5wZdzOvNLxbErw6jxOEnV002YtcxY7Mn,iv:3cpyzFm3fP817BZwh56zy2kcx3EgJ2yYmgzmxEVNgQ4=,tag:ijWUgrZ0CTx/ByHasaZ/rg==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:x0egBg==,iv:iHkU4YWNGUHOQlXEpuiEGn3NPUNntLdTm8X/FqGbk3M=,tag:AI/Omnt7nr+giii78A+KQQ==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:v5i/Pp7sO6qHQw==,iv:wMpyKMHO4/2N+mdKJhUTtK4HRflTdJ7rlY9/QaEVWPQ=,tag:bMYo1pCyZ2pLI7WOtU+6ug==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:ZpdeGRnvWBjJCgpQHd3rwjwPG0Acfuc4U+t4ktfc+qU=,iv:pLVa+RNF0jKuDY0F0Vyy+Ks4soAeUyOlT3mdz4tREoY=,tag:BWKEX9cboxrf4ay9BPKuog==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:kKhOpJbT13leMw==,iv:/QN3kjnktap16d8MfDrNs6zrhvKAuoDvkmdrERgVcko=,tag:Ynqti7THiv5E947pyMP7Dw==,type:str]
  #ENC[AES256_GCM,data:oyqRLIqagiedtpzPbwA=,iv:t/2jeC+DHL0P+HXeaZm4fNWR3mX2Q6H3HB0LrXt/ftk=,tag:Z/6fPsBeeGzA+iKiWSxfYQ==,type:comment]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:byqzhEVHrujC8hVLHDMUiELi65x98wVn,iv:ACqZ2Jy1uRyrURI5EG6epraqdyZdQWvjdMo2KQl6kwU=,tag:SKQ4N8anWwmI4P1LP2CXzQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Q7tT2DORoQ8=,iv:My+LuBQ4+mmNt1sHIwIssQZHlUCP7td1/F/iL1R9glM=,tag:/XRQPVl9xW2R4V2M0rRHFQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:8m7EHa4Qb4hBhg==,iv:GPNzCeXJu/6o7UGxiBB2PNhgD9a+Rxsm8DSnMiLGsrw=,tag:+f/UIZ0POhAgik/w6z7COQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Qr5vp9aolKyHwUBKIPI0NEs39PBmw9rnb0dLS3NXC4M=,iv:pxSF5VKEb89RhBvqp9Mm/L3F0ktpYSBN0T4zNivYSF8=,tag:MRBfIcZ9+cR/1KWeh2F7Tg==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:zF0OUCvNqG2+jTxSTqZAOcJcyzNY3Q==,iv:siiqMiF5+g0x7AXdawFHUYN09eVhTTXBoP5dLXIdwLg=,tag:K//hd0K89Z3PiC5x4aw32g==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:m39rIaKG0R8VoTivbcQ96tdIhtBpSw==,iv:LPv8oEn/Uc/T/lqli0FJJ12IqQ1Dnek/Omzuv+toluU=,tag:zRTVklEBS/AmRud4ZD/qsQ==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbjhVcHp3ZWhGUUVvYVho
        RE15ZkRKbitJa3VRbWxDdlFLbnYrOW5kZG44CmY2RFZwa05MWW9JVDVzMkJYdUVs
        KytBdzVoL01WQzAyZ3o4VXZ4cE5iWTQKLS0tIFJKYnVvZG8xang2blVUNzJYYnVS
        NWo0bVBPWHhNMm4vdzJER2lFOWZHdkkKt1u7lm0x5CG+/Vnf3Ob7WavulxOUORdQ
        k2BzXfUdvLVoFIURBP5Zybjn13EmVnte5uQ2y/LuV6ofcmlroodyNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-28T21:39:05Z"
  mac: ENC[AES256_GCM,data:knS/qBs1CbuGBTlRuM8YQrbsBNsAWYKFLf7N7IF7OR1WAxSWzaRBIiMSNYriZfHz1grE2vRh4yuMeeWz+GUdKv9wen43StEouP+EQxkKHA5OeSFoVIfxIOOCSK9RQOtCqpkvEoup7ksieAFJkwXoUg7wcYUPOg/UcWPCBP3o66A=,iv:Q9RL11a4jNJN8jl1vRN6S0Ok13ikLYvlp9TOO0zxD3k=,tag:sfExUpVO+R9ds0QBrMdBUQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
