apiVersion: v1
kind: Secret
metadata:
  name: ghost-password
stringData:
  PASSWORD: ENC[AES256_GCM,data:Evye9re/UKwVJ8qQDp/M27gdhbU=,iv:iT3E8Ouq9uiRKqXwSejSUpTWINakAeDWdKOK7bovc90=,tag:QUChptFoWDYRIqTV1DFocQ==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bVJ5Y3hrQ0NYVG9jTjRu
        ZkpWRXVaUzEySGdxSTlCY29qeWs0ZmpiRWtRCjd5UGlGRmNBUVNvSU0wd3RxOUFu
        VWJCcm9YOStaTGFMS1ZNWWNnWU5zencKLS0tIG9EL3BtSzBCWHFLTHdXZ29UWVEy
        ZENKYmhrb2FnWURkMmhMaE5WdXFWdUkKcYmnGdSYh7BH6CAodKoUxt6S26LrC5dN
        eWJGqbwHbn250HROqnp0z5Ih4f2M7fCMp1ZjG4KCsGQxpeEWVYkquw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-28T12:52:01Z"
  mac: ENC[AES256_GCM,data:FEAaMG4gEs21N/oSAh1OmhuyNzGr98c2lvvzALLmgXJFzEjuToMCZWBS2qu/2NTQa5D+1U/ZvbhDG+MpIjUhOIARyvUqcONidG0ectx5SpjqyXsGcFZ0uIZCpjoyNeUn4nuoiZJyi5ucUCL5fJqy3QZW/xS0SwW/NtZP+7WbTCU=,iv:iQt39i2QFIeaMKXAHPD+920hRhtzSPbNhaqLowrFto8=,tag:+7tmm65ccgiMSE+K48NpKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
