apiVersion: v1
kind: Secret
metadata:
  name: grafana-env
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:td87vfmoR8EHKs9NQfmaC+duJt+85KrNXmUeq0Amco/2xoYeHmP3dA==,iv:txt11T4PEW8IV3IxNxDJ2lmAdQxfKqtqmoVOkJZnkpw=,tag:9IJ6rnRDWQh5irwb1MKwPw==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:kkgFItTx4DNbQOmqbj5Fyl+GjB/jEiIoy4m5hZJWW3foHWfkLmy09R4zepEVdAbFWmvxwwVoNsnkHxluynIhJ+zg1qhdqkNB9mQqEApiDnE5Ob644WEfIbRqLn+dsRQE1ouisMi0NTj3kPJ+ZkIoyMKFVvOYkcTDiAsL+FFmKPY=,iv:NDrqJ9mwPTWQmOn4UDUAk4qK6+BHUvF7Wa8KQ3pqSLc=,tag:4FtA2gi6n8sjzbS8sx7mEg==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYVBUMzZTNTdoOXRxcXIy
        OWVuRUQydFg0aTY3YWhRaFR1U3RsYTJleEdBClBsOTNHM29qZ2Y3RXUzVFgzTnBB
        WlVEWStselNBK1ZMaTdyVFpGYUtsUm8KLS0tIE1YR1ZjV0hVdUZOWVZpNnZlbGVP
        THpTYzhoYmJEMHliam5QU3JQY0dxYkEKveP0qTllMTLwgI/VjHAYtgGPJ9yFNIW/
        tptX1lkcnU+Km4lo6L3QjELS5TEg1LdHf3OPgF+JU423gcupdYnHJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T22:18:37Z"
  mac: ENC[AES256_GCM,data:qNyDYSszBPAKlWoE9xHMvMj3Rl0f7VLZKH3UV/0mIKwHLXtcVqN5XW3VQcYLz0MWrum/j/w9zIhDvL+697KMtGhWn91rkcGvGITeIvhKkl5Gd/N57DPbBpaLK/JXtmKqeqW3Z4Fr4/jzAC/ZVv2ejZBAoISAb3W6Z1CH2z2DvTg=,iv:VJyuDAzXR993UpAvCBh1tNYHv6lUnJ/mwyyH+3gLUlw=,tag:no9jHVhjAi+/DwLvP1ujOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
