---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./emqx-operator/ks.yaml
  # - ./mosquitto/ks.yaml
  - ./matter-server/ks.yaml
  - ./home-assistant/ks.yaml
  - ./frigate/ks.yaml
  - ./silerotts/ks.yaml
  - ./wyoming-gigaam-ctc/ks.yaml
  - ./music-assistant/ks.yaml
  - ./espresence/ks.yaml