apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:sK9rIJj4gZBRb8k6Bt06sRI=,iv:6spnL9rthCiPnbb1m3XzfjFkcBiryz9gaTdZCUEwlSE=,tag:yenoe4IOG4koP+ecnrrpiQ==,type:str]
  SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:QVKoeYaD87gtN3RfS+LRBgkh7IGMWF4xW+N8NwPG99MAFphy1pRZ0w==,iv:MRj1HbFYk0p4I1nfuhtv+2fiYXTyteUlq0fdWLZGfZg=,tag:MvuzlonA9XiPx0cX0eJwbA==,type:str]
  SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:B2JwaA==,iv:MhNSZI4bJR0foUPq5/F08bREX5966O6Pza5hZSYLK0c=,tag:YokXcHz+xPb6lX2tvXputA==,type:str]
  SONARR__POSTGRES__USER: ENC[AES256_GCM,data:8XV6uXdxP0E=,iv:Z/vqTuVpRXuXKiRg42zrVomu37BSv2Zwf9dt/MpfCsY=,tag:vG3YfUFdD1hx4FF6oZlSJQ==,type:str]
  SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:OIOBKFRPjcylUmD55w7CNFMQ/h48,iv:XjzViVpaCQ7TK9dpVlo0l8iShh3smpBqHGzhzjvxe5I=,tag:X7Ocr6djZZ83h8sHxN3TvA==,type:str]
  SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:S/Un+X/nBD6cJs4=,iv:8pbAbE6qgBKP6qX6fdqrZ8uXb1d1de0S7KTk6fr0ar0=,tag:Q+jQckWqGlI9pBP95gdPgw==,type:str]
  SONARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:edLO2bMX4MUHfw==,iv:LrYj+hjDlZMOBxjWDKGcvJjKYjcqQsRqyoXdKpkuCC4=,tag:Gv0xIaEfHlgvne5dzNdAIA==,type:str]
  PUSHOVER_TOKEN: ENC[AES256_GCM,data:58hTOo1e48y9HRZ43rpg9xfg769OBzC7,iv:HYVKP5ZHYAKUKCHjgM4hGyVnuZqUS0tlbQQgNLufnmk=,tag:9nmXNuRyQHQeyjI6QdRs+Q==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:8HegiGM6VVtEQSFjexW09Q505H4=,iv:Hxh0GavT132wK4WqIt1H8ZaqJsWHRqYt4GOfbPc/oMQ=,tag:1UUoenJvgYMICsqqpjrcxg==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:UOHJo4x5xGsN+qBxZHCiM3JmlCz2aQ==,iv:N0UGgIR5b7qhh7bYzpb8xbCekYJ5hxtLDqpBw+c9TQk=,tag:YVeHCbx8+Qu1kAv1RK16Fg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:LelwFVHlHyTTYL35EP49W6spDAUP5h5VpKG6hbDJYCkdt4AO4XbFag==,iv:XOAEpCPHtbTid19xdOWFuML9B8LtfpgB8x0LVLGnUwc=,tag:rD4N0OZnhAFqmnb8YDCcAQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:NzkWsqE2paU=,iv:10Pi5Ym3Nj4PjyVRKKI38MUyAIHDkpMwkVoCykn4jbc=,tag:YRGGKlI2KIYwwtCvHzmZiQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:+/I7z1O1KSjX9nC5qt2aDpKRtEt2,iv:28fpv/9MSgK1njEaK98L/wbqAqzzcCEbvEuicKnrs8I=,tag:pDV+N3ZtGg6ogIUBdoPeLg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:fMf0py1aEkN0UT/rx5GEbl4fwCm0dQ==,iv:9DLiCfo/QESWPN4hFhcw5pjE0gqqE0c5qeuCkrhajmg=,tag:OYjZMuuQ+RCmM0cEiMFOkA==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RkRtTk1wVEhFS1NpRkUw
        UWx1aHNBWFRHNXVUajg2MlNjam9GcGt1eVQ0Cjg2ZlV5SjZmNytzd05FdFhSVDd2
        cTNXaFhBMGZMNkVybXJLNFlhb0pWcU0KLS0tIGNOZWZMTzlKcGRZL1ZIWXJQc1Z3
        WkdOcGxHM3duNWY1YkhvK1RDOXZ5R2sKnRHlGP9327mm2XUt/Rsfmw0hSSYMQTQN
        qwGnDzkDMngdIy4v8CMVjIeQn1sllTl0gv22Nj84H2DlLi5f3l3C0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T15:28:47Z"
  mac: ENC[AES256_GCM,data:id5R4yotYNx6DmFDavZpQOz5n1+xXvRMNYuS2SUlKf2c4kJ6kLa2DdM1FPHT9A4wabNKaX9UvJ/3Ponc8mD+Qo/agVgY4mmJOJMq0wUAMGeJmV9i60HKPFmsTIAo6RMnEIIu+BZDJl0tbeM38uxC3dg7Geg8xyTIx6uGMMmgoB4=,iv:FhuZGQQYaFyOkYLxB9hZbk+NdKw0R2IJngJKaZRYL+c=,tag:tbd91jFGYvzg+ChFxJ5jPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
