---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app emby
spec:
  chartRef:
    kind: OCIRepository
    name: emby-config-at
  interval: 30m
  values:
    defaultPodOptions:
      runtimeClassName: nvidia
      hostNetwork: true
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 110
              - 993
        containers:
          main:
            image:
              repository: xinjiawei1/emby_unlockd
              tag: stable@sha256:3cb78fb80eeb0d03e2b1f8be8f1ce9565a298960a0dcb11aab0e26728b2d9f44
            env:
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: all
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: 1G
              JELLYFIN_FFmpeg__analyzeduration: 200M
              TZ: ${TIMEZONE}
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                cpu: 15m
                memory: 1837M
                nvidia.com/gpu: 1
              limits:
                # memory: 15G
                nvidia.com/gpu: 1
    service:
      main:
        controller: main
        annotations:
          io.cilium/lb-ipam-ips: 192.168.108.77
        type: LoadBalancer
        # externalTrafficPolicy: Cluster
        ports:
          http:
            port: &httpPort 8096
          dlna:
            port: 1900
          disco:
            port: 7359

    route:
      app:
        hostnames: ["emby.${SECRET_DOMAIN}"]
        annotations:
          # external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *httpPort

    persistence:
      config:
        enabled: true
        existingClaim: emby-config
        globalMounts:
          - path: /config
      transcode:
        existingClaim: emby-transcode
        globalMounts:
          - path: /config/cache/transcodes
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 3Gi
        globalMounts:
          - path: /tmp/emby
      media:
        existingClaim: media-storage
        globalMounts:
          - path: /media
      nfs-media:
        type: nfs
        server: tower.local
        path: /mnt/user/media
        globalMounts:
          - path: /nfs-media
            readOnly: false