apiVersion: v1
kind: Secret
metadata:
    name: mysql-main-backup
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fE6NxANR9AUB6/kD16KvLjrnKuXg3WTSK1CnuTec,iv:/gix6+YbhR+kt6jXuzyVBZgIQCLiKhmtnbHxeejiKjw=,tag:xp7bkmNBoGi22ICAlayIxg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wICTyHbnccUzsXDXZTdS5xaLJVNR7xaLAiFa6i/I0fe9,iv:buGOcFZAtOZOGVOkCC+O99VwBt//kGJwWgRriJ+VNf8=,tag:IARoPog8xpP2ymW84BI01A==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:R733f4QSWIPD6rNOfZE=,iv:aVYVKGRKRDCyuQPucn+NNX/XiU1g1szBRvc820IK2E4=,tag:7BKYbodOb31bSr14ban2oQ==,type:str]
    S3_PROVIDER: ENC[AES256_GCM,data:u/zznqM=,iv:7RTe/w9wr6rWDRPivohzly67mA764ZynKMOkJQCfT5M=,tag:ivns+N/N+6kt75mgRu3djQ==,type:str]
sops:
    age:
        - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcHluQ2Q0cmZwYVFJWmpW
            dS8yM1RCbitWV0Jma0hlZjBUbWxVN1EzVlVzCmF6YjBaWWRMeFRodnB0SFc5RjZq
            bnNkd1gzUmFoTkJpOVZHVWJwSmVmeVUKLS0tICtraXQ0N1A3TzB4NXFnTXNaSVZ1
            TDFqcUt2Yyt6dUJBVkZWcUJvZFVvMTgK1+a6NPFMl/qaR+twVikeSDM8IZKwfsPs
            RC/UbVnd9PhzkGzj9N1wJybAjcDu+AjdUCA4OGgFqRRSXFnEGkc9kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T13:06:32Z"
    mac: ENC[AES256_GCM,data:EaJZnvP6PJXS5hm9+vhapKCWE2vle4blnVuBQqiTzNJ3laoRowctlRAKu5ZhZaGMdfAf44GDlxqY2TU0guKTBxC04bvY0TCCwMHNxwDL/Cok2Rtz5TSUbTUR+A5k2sHjjieE55A2aO22IpKgxB/WU3pBglgNEBv0RR7B+K+rcew=,iv:FSkGwON/sZKbtosu92fJQVqOwxjnSsxLAMSLG72eziA=,tag:tXA5B+DmqFrp/sRuQrbDEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
