---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: main
spec:
  replicas: 1
  mysqlVersion: "8.0"
  secretName: mysql-main
  backupSecretName: mysql-main-backup
  backupSchedule: "@daily"
  backupURL: s3://mysql-main
  backupRemoteDeletePolicy: delete
  backupScheduleJobsHistoryLimit: 10
  initBucketURL: gs://s3.casa/mysql-main/main-auto-2025-11-25t00-00-00.xbackup.gz
  initBucketSecretName: mysql-main-backup
  volumeSpec:
    persistentVolumeClaim:
      accessModes:
       - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn-fast