apiVersion: v1
kind: Secret
metadata:
    name: mysql-main
type: Opaque
stringData:
    ROOT_PASSWORD: ENC[AES256_GCM,data:lXRduIc5KL1D1NINWMwZBQ4Qs5qHlIQJKaxo,iv:k9rN2cXQQPmOo+EuYwufwF/25hYLsu7Ee3R6mKOFAKI=,tag:d4fPWYE4y1tVOKAFRjZDmg==,type:str]
sops:
    age:
        - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OXhhakkzemUyQVdvakhD
            ZXExMmsxc3JIazVNZk5oQmk2ZnFwZkJNd3djCmdTYUQ4cVZqdzBxRnE3ellrS3da
            c3M2NFkvY2dxdndYUTk4RzNabkoxZzAKLS0tIGwzMkV6REJQbDhvRGpMVWJ5VG5v
            ZTkvRjNpaS9CR2NEVXBZdFVydndSVncKsGzs7pvXiWE0mE/EwoLcF7rzgOGBeh+D
            LgrToYIv0PN8BweVDfWIG0pMcH+l44De2aImnPf/x7Un7FyZejda/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T13:06:39Z"
    mac: ENC[AES256_GCM,data:8zxZRxHraz1Gsu105zI5FtrkuFjhluX9fwigr+fKksbjxLV7POCbc6PGVgQfPFEG3+UCnqj32syT1k+83EuK/tHMoMOf7JBK66FErr+EIgRjosqM7wFe5BvySBsjwSufKLIFrAk6PhdueeUF8kZlynsgDuPMirRSWmcmrzw++cE=,iv:cSARiNxtDuRDpJVt9WOU5AXyvWTlpb8YaX1fLgtOzfQ=,tag:fVs5y8R5DxjYfkshAJjXAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
