---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrepository.yaml
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./secret.sops.yaml
  - ./webfinger.yaml
configMapGenerator:
  - name: authentik-custom-assets
    options:
      disableNameSuffixHash: true
    files:
      - assets/custom.css