apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
stringData:
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:y6lDJwXt0jIcCA6V/x/i7Nt+0Or3cXWme6cmOBkm,iv:pg8xWBpMvXm6wXyExqAGi/9gDXUe7+9DOrISyM53IqU=,tag:t0zqIC8I0cgKhtDrfkQvDA==,type:str]
    SECRET_AUTHENTIK_POSTGRES_DBNAME: ENC[AES256_GCM,data:hlFAlWeKpHAE,iv:1QeaTEmQAFAXP98OAG0RmVEekAEFII+RDa0zCduR3jM=,tag:tWmVCk516frH3rFdWCLjbw==,type:str]
    SECRET_AUTHENTIK_POSTGRES_USERNAME: ENC[AES256_GCM,data:FSaM/94PCAX3jkmiVgmnpnperd2loMZNBJVzkpAjykCmllqZag==,iv:GMmzvdfp7cxt1e1pDIsuqKQQTXJ/Eth3XbjM+18tg6k=,tag:w7t4V/5m1aYHUVhyxeg2og==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:LBCKltcFhA9VoIX81RbJptUpODGEiIbu1FHXNnUD8aUBj08KYg==,iv:rDJ6cMmI+eunJcp0UweI1sHnvGeaLGJZwmJvovQlIvc=,tag:23QpRo5lgBN3T1yv0gcvvQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:3QhN0FcgIXnx,iv:kFBKqe2Uxf06bUpE1U2N9DwjjAcq7ElYAhi+mJZUqfw=,tag:xtkOxRB93lodkhpoWS3TKw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:6cqdxnGebhJriOxPhd+XTCLWIqIsITz/5zR4G4Nq0TmSaSsOalgq8g==,iv:fm6iZN4U/aCyDxNKV+CHDzolkaEJsq5Mshtte7aj5eQ=,tag:ErTHr0kCqNYQsg7f8GkEGw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:L72BSl8emv26BIwOiFteVKC9n+NqJlLOEPTVvDVhwgumpwsY5w==,iv:Zsd2AIEZkuSTNl/s8A8IJxuYrcwMjFbeQfsIeOFFPWw=,tag:SnzoVi1hxJ8Vqt843H6HCA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ikLBLiuz4+h6VnIRNWZIZUF21dvq/+/Fa68CF1rxndtoP5WmnA==,iv:bvLPfMD1qnEtEqCeoPlbqaAfSbR906dKGyHnhTyx6fc=,tag:+33BRNZkLVxTfrBkVKrYcA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:8o7OUS0piGGldUcImcDHfL8AsNUakQ==,iv:0444eFF8pUHqcueMutbQn0q/f8h+gJXcroBPqjrW0xM=,tag:cwo6HNd0YRqKBUy0KpGtEg==,type:str]
sops:
    age:
        - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSTRIRFgyRHNacDNhZk13
            Wmt5MFVOalJ1QXljSUlOaGtSQkJPTG5qNGtnCmc2OHZKRnFPN0ErVXJqbTNIN0I5
            R25BMFpVRFIrT282VjF4L2pBbDVtbUkKLS0tIHJYWlNqSUNUZnBaRTdDRVZ0dVpa
            bm1qZHRVZS81czZZOWFWU1k4QjdCY3MKwDOxxxTbhE2VP5tpq+PSfdYktaiI6KpU
            OBrDSip81JHOXhJsfmFpwVOq+iw9DE8WpwTwUydU3JYrIwGEV7SQKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T21:17:06Z"
    mac: ENC[AES256_GCM,data:QVhvGchEvTTeJOseaVQCWXrzK2ZmmkEpyqHE5WcJyJ5+kExZRXfx0ECOrdCjsv88S+SxriInesD2Ch8SAb9+1/hoP/D2awAIbNm3EbfWPk0DmMNKHQ7kMcbz36eEfA4B8l2kjeFQDNIA1AZegyT3wer0OCnss1lyHpv5DnaWR50=,iv:42NC5OSzl2wYI4E3zzPKMdRAZHNv0KU1DpgDfnI/49A=,tag:sFYizcwuc/iK8Ni++g5Usg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
