# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: webfinger
spec:
  chartRef:
    kind: OCIRepository
    name: webfinger-at
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    controllers:
      webfinger:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/gelato/tailscale-webfinger
              tag: beta
              pullPolicy: Always
            env:
              TZ: ${TIMEZONE}
              AK_HOST: authentik-server
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: [ALL]}
            probes:
              readiness: &probe
                enabled: true
                type: HTTP
                path: /ping
              liveness: *probe
              startup:
                <<: *probe
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
        pod:
          securityContext:
            runAsNonRoot: true
            seccompProfile: {type: RuntimeDefault}

    service:
      webfinger:
        controller: webfinger
        ports:
          http:
            port: 3000

    route:
      webfinger:
        annotations:
            external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        parentRefs:
          - namespace: network
            name: envoy-external
        hostnames:
          - tauth.${SECRET_DOMAIN}
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /.well-known/webfinger
            backendRefs:
              - identifier: webfinger