apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  #ENC[AES256_GCM,data:xB4KqaH9xA==,iv:+Bvpt4ewUX1qI2SvatWrcWHluusbMwDUHSDO7VuRUXg=,tag:uEADucbfJtGvSnZwQXHXsA==,type:comment]
  DB_DATABASE_NAME: ENC[AES256_GCM,data:ouLMteUa3ok=,iv:q9jsAAi6LKlJ6arwrvI8yceGp8I0kvrYYAPk06dZpkg=,tag:af7ik3XeReZMVbwt8GRUOQ==,type:str]
  DB_HOSTNAME: ENC[AES256_GCM,data:sGhxf1GVzdpDe02Gcrx3sgh+pelZfIqOfNodPI6Pp2D2dBHtpYvhMQ==,iv:Umm65B848IgeVK13vQVmx4Z2lAXqjOt//DYJpptgJco=,tag:AmdrERpVCbhjb5b8QJFddQ==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:YzZqDJjSFl4o9cfT/aHWDMCz7duRtA==,iv:j2np/0t/GJwq7rhh5p4zOamL7jd9CZz71bjqiRb72sE=,tag:VfLHV3s/1B6w08dX8X4Y4Q==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:ZceHs3dt2gB1rSpcRwnPAmJKakpl/w==,iv:5upH03WDSzb9dEGcR1EcQprHZeUW2jLZ0VBf3aU8wCo=,tag:hDMqsIyxmpPE9YTGh2nbIA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:SvrCNYecQ8V4aXKzMN7JWvdXJyk=,iv:iCSFSYH/Z82jmwMEgzXDQgcQS6P5RSuslt2065Aaojc=,tag:wghK6zVvD6Vpuq/4j+Thqw==,type:str]
  #ENC[AES256_GCM,data:hDDE4s8LrNiZMg4+u64=,iv:2T052Yw7XSKjpxghU9x841ldkaltpZO972qlmae+ct4=,tag:VCC83UlvwGOgO6y3yZB1DQ==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:spGBbaHdgvU=,iv:c+l0dLMGPVR+njvjYbUE3XttGUrX31DlrdCNgNAFVDQ=,tag:fCMBZc8vc0lBf1znZBichQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:a4RycJX32tb9YHFpfWKn2tT7vKm5B8YkbCmLQqmpuB1X1lGAIhEtUg==,iv:qWnh7WiAI9w1bOrQGAbv3kt4l0EGBtTdEk2+eS+RMtk=,tag:3rykJCafABDTX/X2mQxmsA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:JTwxVdTJyzlFpQ==,iv:HJombgM+XJ6NaP2+MJjTmCNYYq9VdjfoHdGMYQqR7bI=,tag:gv3XRYssvwF42tEDlLJYbQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:OD/f7w9o18BIOgNYvMTZjgQ=,iv:bKVJsTkmS1cU1LCrrhyHfUzDCC2JG/QmycEqGHG9KM8=,tag:P5jF2J36qqy0711ljBrLYQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:ycuHfSJgDhM8+1TI9+krewNZ6llDNw==,iv:3OI97jj2OV6ql8xuwPiGPaiDLeaYfYBKw5CQTRamuDk=,tag:9PXonlJkEK4uWgdLDcAFoQ==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MThpcktUTTJoejh4U1VW
        UFhRcWlqNEUyYTNLSThyYUxsamk1OWhKQ0RvCnNGZE9ELzRSSXQ0ekY1cE4zSmJW
        cHZlU2c3Tkh6eFM5Zmw3UEdsRmlVcG8KLS0tIGd2TUU0TjVUY1dyZTNEQXU5bVdz
        ZDZVNkhac2RBd09hQWlNUTVtU1RqSDAKhT7NZVuzSHiFPZ9kzzsLrn52fkzelJAV
        tcYp7VksYCY5urgW0urpZDyHEbtHDZB4+ykLSMDz2/aZO6vIBvMmsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T20:54:47Z"
  mac: ENC[AES256_GCM,data:mIkSGFP/p0CK4d9sLADK5fOR+iSviRngEJmwcm0UiktIfMRorB2cZwjk5BnUyXc7JJcw+ShZMQpuTE0d7aUrRSTgoSdtunYwk53LB42Edi+yytKdp9Xj0D3igqQRjvrxxN9/J4MD43QQXx6glgcjZ33hlAMuJigGOKpLBEEYgaw=,iv:9cBV2mMn/dM/wBlU04pcwwnUzQwBuM43QODWxnborcw=,tag:e//ZJ/pUnRflk/Z3P6iZ5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
