# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.5.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jackett
spec:
  releaseName: *app
  interval: 15m0s
  chartRef:
    kind: OCIRepository
    name: jackett-at
  values:
    controllers:
      *app :
        replicas: 1 # active nas
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          *app :
            image:
              repository: linuxserver/jackett
              tag: "0.24.268"
            env:
              PUID: "568"
              PGID: "568"
              TZ: Europe/Moscow

    persistence:
      config:
        existingClaim: jackett-config

    service:
      main:
        controller: *app
        type: ClusterIP
        ports:
          http:
            port: &port 9117

    route:
      app:
        hostnames:
          - "jk.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network

        rules:
          - backendRefs:
              - name: jackett
                port: *port