apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
stringData:
  PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:mDyDirH8HvLNYG/d+qswmxMNnQ==,iv:9ufBi1lCD+CVNt33rqB8zW8wtwIJoEu8FThP0M44DPg=,tag:fN66qrPfr+4jcz7N1AKy8Q==,type:str]
  PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:fHEpLsi9XRWsVkINoOi/WRohwkPeyighfPoDXw1ti4f45PKgPa0oSw==,iv:n38eG+AKZM7xdtCBl7dfOTeRXmfNdHyXzJS3mfX97NU=,tag:6/eOuiM7bCzdfYGR82eI+g==,type:str]
  PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:eIdnNw==,iv:RKb05UkuiYKowm7Mtvlv6zjBAvx1CimZ1LkaSm63q7k=,tag:+6y/TTUh+07Th04YQ/thNQ==,type:str]
  PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:kYtbKA2Gv6MzlQ==,iv:hmouFYsWLBPq6rDxZgZRzf3RSDm8bFZuvELbOJF9ojY=,tag:OIyCoj2ov/mAgqTh407V8w==,type:str]
  PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:hhQ4PAkT361hThPBEVgYb2stW+wDTUk=,iv:pf7McBmv2tATRVHXBPM9d/TRhzCgbxf4Pqnb8Rt6BEM=,tag:qv4Tm9V9H3GcggiMBzaWjw==,type:str]
  PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:a+N7TU/6oud9yHRmIw==,iv:MOUXeLirJxNfCnFTHxn3VOkLemaaFQU45GJCQgI8+EU=,tag:IngAQcNoHS4t0ngQt2udLA==,type:str]
  PROWLARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:SCCzQtnWzZ272nV9,iv:eWlpnJdP+UTYQK3eGpSpTG0X1G1WHbVFu3jHZq+TJ7o=,tag:981JQwG9iG+zB5tv6CQIsQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:hNZ82nau68G7u+ue208KwPvBJWjnuOfqPNI=,iv:eWL7MpGxgMbq01KrxqzLYEQuHR0KIyjfPzzlcHcYPiM=,tag:eQsu6amz3vESJ+peHlBviA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:pXsjB2k107+VRdvlpCDSvopm0csGhqt1K/qg19wQY0b4ijuJYQZWkw==,iv:mRTB1qRoWapG1Wo0rQuqLqxqqsIJUp9Id9qLHGwUm2g=,tag:0Pokgnr1E0N+SrHJhMVDmg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:EcO6cYrf3oQyNg==,iv:uQTmVbOC9np5XgP9ddfhd3Ilz39J4b9gGoxaahcrlFs=,tag:G1W8qwLo3ZTwi1RffaIEuA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ieusphM8YcmjR/KdRGX3Od5xiaFFTWU=,iv:U/aCd6vEUYKpeQCUyeEphDwb44fxtjKxy3YAvy7G1tg=,tag:OGCZLRpE9Yj/mV4v/CAhnQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:rUqDPBFDlSeMg3XrwJl3ys7hVfjbmQ==,iv:lYg5wVixCILA1NcC27hKtlg/gRFnqy1NXBEhe7Xah8s=,tag:rMUdLjnO8+cAOUk95dgvGA==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWTQrdTRYRWFveUZJeXBI
        RzRSYVpzTkZwMHhidkVzN2JyWEo0VzJlZEhBCi9laW91eXJBZ1RXU3plV0hoeWY2
        K29SNGxMcC9yNWdyOXlYNjFjQWRFaHcKLS0tIFA5YmxMVlNmK29JbGtwMWZtSVBh
        NjUzUFR3aDZ2YUg2YUlNdTdnbnVESHcK50SgV5DOkzPuTlQTqn6q+ypmJf8A5HX5
        qMQOM7QG+EXDjRP1Yu1znwpi8fJe5fqIAxs16K5EqcIf+zuUfW0dXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T14:44:23Z"
  mac: ENC[AES256_GCM,data:8tGZSD0ayRwcGMWLea2yUyxhvBMzSLQp2v+aX3xDDghcoIImHny/5vsWz3j2plZrj/RCLrvfcxwMd85N97TuvBxumQ7Il5+BqkxudaNwFa+AxZr9xaP7JcYNr1I6EAf0i49JhaSTjRQimgE/EAHlcJif4QYeg+U2mgL7eIx9l1U=,iv:vnuSOSUtz5PNZwSRay1VhQbLis4vwkdJ3iHgqkltJ68=,tag:Ps56Ea954ePfXxO2VOI2GA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
