apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:SFrXhT4w3J0QCFPuPLABTwadhVQvWLwH5cXYbj5Yn52alXg1MppHqUoIszttlm0F3X6t9EiCdZp3ypIPVTylHWoK/FZdevgkx75UvbAwdReuUWhfTECt7OpMBmNjt0LdCyTpTyqqpvtd+2Z44DVfmByodgPsOsA/O2/HsbPig/nyUav4055Q+q0Lkg4NRXkv0x6lKkhrpN5WldxLmN74hSJfIjDY1RY0QV64F6qI60xO7NN4,iv:FEcN3Tw8nZKu/9OKrOK7rlMMqI4jNs6x9zVf5ht2GvY=,tag:WUcL6H8Uv1d1+aXj7fxWTQ==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VEpCU296MnM0d1BtTFN5
        VkJPQnNlRk4yaU5LSEpvOHNmTUJWNU4vLzB3CkdwWUpLcVkyRlV2NjNSSzhTNTBn
        Tm94K3NNWGdHNW1DdDN0cnQvcC9CMWcKLS0tIFVuWERUZWF4cEJmU2s4bWh2aEdO
        ZWhFSzN3QlhqRHVlbFFQOFN0QzduWW8K3+bUXR37fVdXDITvgmo8lKiBkI/3sxZr
        LCglczPVmX+qKPYrKdlQOAyO5a6sxR66jbzcJc3fk85tQfwHKHHMig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T15:28:13Z"
  mac: ENC[AES256_GCM,data:DDxmeWep/l8XH+gAt7V17Rtx0mde/WY1cQ9QKZErv7rve9xwC5+SS5Z23Un0z6cqoWZThMUAzKXvsK7jzSb2zsonHYjMCzJA6XD2CqhYjrGu26Tt7xh37ldyTcf1Bi7uAfc8/gmCtOY0Ce3u52FI8Dp+Y5zSj+tZdddVHMiiRpI=,iv:Uda3tDF5p60TGiSQWD9xOFMorr/myS13upFkWF7NaPY=,tag:WSzNNVQhUoY232QQZa9qLA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
