apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret
stringData:
  username: ENC[AES256_GCM,data:lQ4LFRSJffL+BUzfVUjeNjhMqA7/HjFRU4A=,iv:CkN36rHHW2G4tWr3n5wiRCun6Q+aWWiZB7s0DoE2V5E=,tag:4qFM3ef1EREpuNmbXiXzSg==,type:str]
  password: ENC[AES256_GCM,data:dyVX19jyyac2d+HWJ5mmlLlBhhHfV6IIKqw=,iv:NW8Rk+fVAG6njfnknY0KqgjUTXTf2I4jVBVVzxaa9wM=,tag:Wt379+m8vOfdJi2gYYvgRA==,type:str]
  mosquitto_pwd: ENC[AES256_GCM,data:+uiRJOFhqFN5tZ7wM1N2A6OzvXQqFOPz5BJ4KpoeaGlWzBofYyNx/PWeIoAPEhy+2mtTMBA=,iv:GjAA79B/IWhOoOkoOKbS9wfkFzGf3C86JRSQhS8MIQk=,tag:Vec5zaOnh2m2p5sX76e8oQ==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SU1YZ2VwZDc3K0F3VTlq
        SWxER1ZrS2hXcERibnZFSnorN242U0lFYW1VCkljNUQ0cFh2RXB5Y2ZsRzBqQmRM
        S3VRdUJ4T1BrNkxvUDBqWHNzMURJTm8KLS0tIFNYZzdzMHNZSmM4WWpJc2NrSUI2
        Q00vWjNpMEh6TTNvMFltcm1xbU93WHcKkjMLHVY3kw0rKDyMlQ6H+NzaVBLPrFlL
        RxSQOBMMgWGuRbONXzBuZZYlnO7u6lGjGbuq7ex7Fcozfr8Yd650Pw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-28T21:39:05Z"
  mac: ENC[AES256_GCM,data:Ma+VlvAJ4Qz8+tf9oV0ntnoRu7o3npF0hGXC+/JhaP/xGfyMenMCeLu4iuAXwzX1fi9iT66BHJS7n5zAZtO8W2Q5ZLq6x6lAcq23zl06aSnSXjDLuvy28Lg6vdNAvvY0lHQYwuOPkXmUjwQNqDWKjrXp7GVfp2YeSmRb8I9Tnlk=,iv:JguemQ1z+0xK3KWC69CdrSy+8kmCWV8R04QwpYoUqxU=,tag:zeBKq/qahOfBVH5lksrXRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
