apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:1H22mutvf3DAmHBnovsnC7w=,iv:BF+GyBtziSBf1kUhIVqs2zbI2fvFSAw3+80tBTgnLtQ=,tag:9UsIRZt0kq4rh1fLNxL7Cg==,type:str]
  RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:cxbIEYFX9/tHMti6C1jT78ea2ISgLwlikpTpMXRkTUZocfaLdA4gmw==,iv:0ErYPts/aCDMWN8R5odQflNy0ttyq/jQsdt44C0yzMk=,tag:XvsJrA4BOg+7dLGb4RuVpA==,type:str]
  RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:JVjSBQ==,iv:NwxMfr3unyAYSSUWROZ6nryW2ynZGAfFjZw1cMAWJlg=,tag:vwqh8dcKQdhCWQFHMoelTg==,type:str]
  RADARR__POSTGRES__USER: ENC[AES256_GCM,data:jpTDGrOdKD0=,iv:hQ4MqSi162EMqQXF8sJy/e2pOegrRlkqPloT87YmXM8=,tag:13Bfq4vroYTvBnfSjRHtEA==,type:str]
  RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:09WMeLMBmBSHFy44UnnzSH00H+DH,iv:V5WsCEF7Wu+RiOB+xhoZkRI5b76psYdisvJVE8tGTpY=,tag:GOtJpQ+SJmVAyLNmT9Lm3Q==,type:str]
  RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:uX3fi+GKJNNQKwo=,iv:etJbRB9F6eTQ6nucESKCAcK8OdXRNAuW8u9G/TPsFyc=,tag:FmojQmPrzm654kpdKDGSYg==,type:str]
  RADARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:h2ava+Ss3Whupw==,iv:g5GmXDODm09WRGhj5R5Zn5qQQNCSb1GALGKesNH9kEA=,tag:Rkfc0eU186YydVpPz8RjhA==,type:str]
  PUSHOVER_TOKEN: ENC[AES256_GCM,data:5z1iYO8l3OE/LgdPrdTJ237I72po8wxB,iv:I5SoNW+j4xAaExRq4RVATwalPE1Pu46LSXUQ1Cij5eg=,tag:EWD2rZyCXpfHSEJgtlEdwA==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:SKSEI8r/BBJKRpFT9/MjwecTScA=,iv:fYavxST6zF6K3dWqhgnIZkG6+nVN+v5+WL73vMMkPZw=,tag:Z1eVddNKFJimIS49fqqmpw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ULCZCKZHXON2jpeL8khjXMEjM+eJIA==,iv:Mrh7Nbvb83SENen6LG38HBsaq7hm2rqq5+r+PaaXVU8=,tag:MenYoIzpE5pGR+VDfT/BaA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:fZ/p/lkRKR1/BrSm2qB5NWKLv5H/HlptCX9/EFxgLQ1yyu/dJRXbKw==,iv:vGSd0hZkfv2i2TDh/DRvOJDVCqkgvDpngMOlW89jrwg=,tag:ttgA0V9avOo3TTzUsTj5rg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:VwbyZt2F+P0=,iv:DrbsZ2LDb2qswYbTizVxeaHaBRChZzca7T7xOnTY0FM=,tag:+pHWOJ7dwFVFRGirTaISjA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:NKuQ94fxy9rr2pIos/7WSdxQu83f,iv:nz2ljd6MTxiqs77x6bTZwB1uKTBU1ZSHSmEmzZ1mhWg=,tag:jkNd0vCTPaOEQXfrWSE6QA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:rrPqnWJhP0rWNQVfQkdEn5PlxLMcWg==,iv:SOTVSYXyN0QaADPBqOXNUEf7FRtLeCGteNOcFoyyOA8=,tag:UwWjIcDkPYnvZJW08uSPpw==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdW5FRXdzZDNkT29tbFg1
        T1JkMUlLN2lndWxrSXQ4ZHdOam1UaThMT3lzClY0ZzBnamRJMXBWZHZ0WjhTWER4
        ZDlhRFgxcW1ETjNWQXkxd01nVWFEQW8KLS0tIHVINjhKWFZnNzIvOWg0blo4cFY2
        bUpuZTFWNnJMME1zdmc0V25WSks5UE0KCq71FbochdY9blfVepRMHVbWGzwn8VBw
        FtHnJxuFhdpYo7ni3aYtZEkNMGqRkBiXyNBBEa4ACACIIcdZRddPAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T14:57:59Z"
  mac: ENC[AES256_GCM,data:7PKUOhuw+l3wzE40bWnYeKqkPO/rGO784QwQz5clVR2rSLUfqddWQgjRMtxB36AXZkC9vzanYLCtIJpYotlrcTug21sdFPHtZ/C24WiVjin6gvpJY/Xfr76mqEj6AE/MmJcWPMguBYoLyBQt560C/n+VwX35c699vS3B3LIBEIA=,iv:ElUC4Gku0OXWiDpuRmatFhnFVkFQMnkYAUtmzK6VbKk=,tag:8/l2iJrw1LpHNCcaRZQa/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
