---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-cleanup
spec:
  cron: "0 */5 * * *"
  task: "snapshot-cleanup"
  groups:
  - default
  retain: 1
  concurrency: 2
  labels:
    longhorn.io/snapshots: cleanup
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-delete
spec:
  cron: "0 */5 * * *"
  task: "snapshot-delete"
  groups:
  - default
  retain: 1
  concurrency: 2
  labels:
    longhorn.io/snapshots: delete