apiVersion: v1
kind: Secret
metadata:
    name: espresence-secret
stringData:
    username: ENC[AES256_GCM,data:lQ4LFRSJffL+BUzfVUjeNjhMqA7/HjFRU4A=,iv:CkN36rHHW2G4tWr3n5wiRCun6Q+aWWiZB7s0DoE2V5E=,tag:4qFM3ef1EREpuNmbXiXzSg==,type:str]
    password: ENC[AES256_GCM,data:dyVX19jyyac2d+HWJ5mmlLlBhhHfV6IIKqw=,iv:NW8Rk+fVAG6njfnknY0KqgjUTXTf2I4jVBVVzxaa9wM=,tag:Wt379+m8vOfdJi2gYYvgRA==,type:str]
sops:
    age:
        - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SU1YZ2VwZDc3K0F3VTlq
            SWxER1ZrS2hXcERibnZFSnorN242U0lFYW1VCkljNUQ0cFh2RXB5Y2ZsRzBqQmRM
            S3VRdUJ4T1BrNkxvUDBqWHNzMURJTm8KLS0tIFNYZzdzMHNZSmM4WWpJc2NrSUI2
            Q00vWjNpMEh6TTNvMFltcm1xbU93WHcKkjMLHVY3kw0rKDyMlQ6H+NzaVBLPrFlL
            RxSQOBMMgWGuRbONXzBuZZYlnO7u6lGjGbuq7ex7Fcozfr8Yd650Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T22:17:59Z"
    mac: ENC[AES256_GCM,data:1UjtxmftBOQQSBevICwkVIMiI27AaAwZgzn8pKm2Njj41GAf0X9dE9oOWxumO3DVLEcqiRcFxxVVxbeznbLB8uVWwsCg6MRbnZee6YBMYTfFjVf8IpF3LTl6/VgNErSF8yeC+sYHW1Vv/xZydhgFIrdkKgvVs+TI+oFgn13Km0Y=,iv:o9+kngXrpfJGbRwbE9bH2WBn44erUOXGnuNK1eWppvU=,tag:lcwHC4KZJbQ6Oxiqibd2aA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
