---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mqtt-ca
spec:
  isCA: true
  commonName: Home MQTT Root
  subject:
    countries: [US]
    organizations: [Home]
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
  secretName: mqtt-ca-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: selfsigned