apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:t5rqs7Jgd8FRRh+SjS34ELivdPRdqqhKU5KH7RYebaDXwzCe1eHXbQ==,iv:pmCQm/SNGf3pP+mBprd2TAdWb27sMwEkRJLrOyzB8lM=,tag:481d5dohrEwshYL3X8g4WQ==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVmROSzlUUXQrWnRodEtQ
        OG11elorbE01SWpIZmgvanRXV1ZwTnU3aWdjClJnOFdMS1pUeEZadWN6SlNSQ2Q0
        VUxxSXg0dHZDZ1pGRXl5VHF4NVRMRVkKLS0tIGhla2ZLTlJBb1FDdERxSVl2YnFL
        aTlqV2t2bjVzRnlBeU4wMlF0Nk1kYTQKEomiqW3VNnq87LN3TnCYIMVRGanCnhYk
        pSQ8tJc952nS+xNygDhrVChzAoHZP1i7lWj3MeNDMfWBlTo1LEcTHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T15:28:13Z"
  mac: ENC[AES256_GCM,data:d8HQjSGpSu7NZyKN7ghU0TcH5ufbVJZKB5l4HI49ObeBwV1lNOuGkTNQm0DA0ZOCXEqkVdQsr0fegjCE/FVgd0aAT2gcZ67pilFFk3SOlZQhLupSzMFi1J2KqMqiAFR6/zIMxJJBaBtQTBRFZN0LmHVbKs+dQy2EmDoQfhaA+G8=,iv:tgwK+psdFD6NY3M9BnB/G8dim68Gw61o/KByjYJnTt0=,tag:TBsPlDX2+D+XCrtU4gQ3RQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
