apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:HeI26Vas9n1Zxkl0bFj6y1GTRVZS/RKF9Xaru7bJ0azVBt5+ueGwQw==,iv:m9vg0+DX6ADnQ1KdT3iaLWDSKfTt3mB1Z/UYBifPhjg=,tag:7owZUNhSDOabdyFFtXmN6A==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VzdKem1LMVEvU1FMZUwr
        ZUI1ZkUzZHJ2c1hCUE91cDU5b3QxWWUwdUVVClZ2d3hJK3VDeWZqM3MzN1N0bjEy
        NE9LV21CNUJjcnNsdkxCUmRndm9teXMKLS0tIDA4b3U2bm9GVTZkb2hHRFpuNE01
        Znd3TSt4UFBGTEFLMDZnYzFsbGp5OUEKpeJSR4MR/pmDgs88VrZlUhtV1L/pcyqv
        wEV6jVU/7Yi54Ckt930BSAlR4KF+qaPNJZglFdoJz9Xe3oMBXQBnjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T14:30:02Z"
  mac: ENC[AES256_GCM,data:uL2yafNBvcB5ypgCB43jiMJiH6SIsiP8vc1Xuggl2cZrfuechgwpwjDgoJDJOkLa8wkakpR8FYWDOcRV3az3iVOBhb29yP+xVLuvQuXrhhvtvtHxwqUkVrqpXVtLjrD1SDKavr5mkilWXyOfzeYsEjuaQgkUWs7YCDRhcdFUXQQ=,iv:PgI8mt6xFx3dDxqLVmiifVF1hRMN3BymjxSJodL/oZs=,tag:aNy7YuPI+BOd+R7EjYrWFA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
