apiVersion: v1
kind: Secret
metadata:
    name: synapse-init-secret
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:oZR7YzlfQALx2m0dk3AfD4ZgHb/4WmF9wUMFZqs/nN6r,iv:FxHcnkaXhY0T11lJm6NN4UxdKbYvL/83kVIE5qWphMo=,tag:WQEWZowxajWHI/PDBWXGsw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:IOIkb5UVxnaccNJ5/tKk/iJ4rRl6HN6rCdd83FBlmm04PmJ3MUkgOA==,iv:Ps8RtDgPKjIIVXNsmyMDhWWYOcikKNTiAytyvFHpnvo=,tag:VRGPsy0FnF5iNLVTfCPt4g==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:OrKmPXeRThX1hdz+UQ21pPQzPGUOWE2asz3uD4PO8mgyEFY=,iv:IDtylKBJ/XBf/h7Moc8Ge428215uHZe1RcN5P6tfGKc=,tag:XJNN2ot4G3gAzmITdFohhg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:iNH9FHZRuKJcnNxLXzT0tDs8gf498AjUAHZMM16Bu3BcidU=,iv:OTj43AQH2q+iGQ7SmmfpBxj8FnlBg0sA1vdhpH5S7Z0=,tag:nwlUvgAdDmavyiJ2YD7vCA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:KvSPfyCwquNH7Mo5Z2KK42HrTqeVQA==,iv:FzhC3kApgp4EsW2GGHbY79s1puKyL7GtL/33w8a7bpk=,tag:RZJbSBXZ0LV/71BHq7w0YQ==,type:str]
sops:
    age:
        - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYis3TzZpMUZ3dDNrYzJi
            cmNTNGZyamh3TENsUDZ2MU50cHdtYXcrS0dVCkYyZmZPRnRidzNlbUlFdWYyb3cy
            TEwzc0djWW50eHNUVG5uOFU0RmpKMFUKLS0tIHFyNDMyWkFRalpnWVVyY1dMNnVa
            KzNCek9tTGlRaVZmeFZrZzFnRFc3NE0K8e+ntMQf73bdUIRinoNcIlecWsUmLCTc
            H0Ie7r6xPcCAmir+2GlFj+0KAg8EVEg6P5byrgbLNyz0cvcJmPEDeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T23:49:13Z"
    mac: ENC[AES256_GCM,data:9tkt1Z99sBxeybrMqiPOU+A1M7SfrUgmv4jjeXY9QEjxQPwr/UoAIy6WcSV+piVZBk/U2GlU/YcS874Y6+R1GuKh10w8BKhBbtdqeI5u4wji60IAXfhYLAdsg44TmJ8rWM9J9IbeiWMK6ozHrHjB+MQSvmFOdwXui9LTcTroQuA=,iv:/Zi2oVMXo/9skQBPMH6fB0I0AISS/xXFgDiIDeh4dWY=,tag:pcGi2P7IjApPAH8F2TTchg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
