apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Vuw1SqU1HwOGmOtqUCGwFqxALUGqLg==,iv:MqdzrlDDuHIAvy24xMYgrshYFVJ/sAhqHodkhY3lX5s=,tag:9cLXn7I0jejHdV/SLsjWaw==,type:str]
    password: ENC[AES256_GCM,data:lQUuQOyOawbbo2bqeBayv1VTQ69p0A==,iv:kk8uS1ulkO5ELSbofcWA0nkOZCto161NfwKsGISoQho=,tag:fRUNOJSXW0oJa0oiwHCnuw==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:C3HGuo4RUJCplld2eJoq3yIE,iv:gYicBolRbRIhUnW/mczvBePkA9T3xXHND2URlLlefLg=,tag:URyCWUYkEfPUO2BzRi9zOA==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:6Ipf+L1XXyQBobsVcgZ2yk7v2cE6sg==,iv:ZlnOe7GbySMCEPhuQ+yF7FWaOhVkoajxF+6TdkyXiTk=,tag:0CaAc7nOdD23WjsgfB7HBw==,type:str]
sops:
    age:
        - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4T1h5dldhNkVVZFlrQ2Mr
            MzFqdnhTc1RKZW5aeSsvcDhBdXd4UmhUYlZVCk5jV0dSNE9OM0RUWk1wU0YwU05L
            S01CSy9EOVhxaFFJWkhFUXVPdk1TTDQKLS0tIFE3ZlplakthS3E5bkhsUUdhMmg2
            czlFN1VmbVk2TWlkZjNWMCtDVFI3QzQK/Tf3wrdHilvurJtvIPhTDVWCUrgw//CN
            qTYNnbDCXD9Cqxpv9jAi0QvoXlIlSozrfsFIAusZypkHVOTjg1grJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T10:48:02Z"
    mac: ENC[AES256_GCM,data:XagGPEOrqwzoxyfSfnFP9TES4X9vJRcCxGDyViqpG5FHLvJslTrqpfMi5JVITBFeZnze+41iivjJ7NeLvIV/gx8TUdVSqV9WzG6noay5alAGSOXTWNHWtrL5uGkiFVp8lot4rN3mnxH1bBYotsVds+l3w2lNae2X0yxjH2B5weo=,iv:ep96GP2ezCfqjX/Z/bAjR+gOfKs5VpFD80SeE61f5jo=,tag:N2uLCp5x+9FMqwTr5Om1SA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
