apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: storage
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:o638l2QM2kYx,iv:mnIQHRZFlla8ke8dkhLTJs101JbZ9OE+D0WOcjTUoBY=,tag:U54z5zgJAlp84jrEeg/3eg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:m0RI8bqViEfdpA==,iv:tnuJN5RVjqBDSun9AtToitfNfvaDbuE7Jy7oF1V9OQI=,tag:PlgWPXJeecjHZmPBhbsKig==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:5ssu/WsJH1VoGYntH8o=,iv:82crcwnP02AObAXs2a+gpTonJk3mgRJexeXgpbZDxDY=,tag:dHCR+N2dDGekWn4AArAC7Q==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZUhMdFdNSHBQSWxUVktu
        WW1VYzZXV1N3Tkl2T0hELzJFaTFvaWZTakV3Cmh2eHE2SDVkT2dQSEtza04wYTRn
        NTV4RVQ3bDJTUkV5cUR1d2ZjNnZ0ZEUKLS0tIEhjeTdCb050ZzRCSkFZZ1ljOW85
        bldvSW9YQ1V0eWQwTGh3Rkd2bGx4U2cKaaBrbsSmG4GlT1vkck6VtgY6Z5N7bvqd
        m3VA87Fc6pJR861jtDKZsgrwaaP0ALOGsJr4gzSqWMMn/R0Uq5Vo7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T22:32:40Z"
  mac: ENC[AES256_GCM,data:ZemAsAtU0CwJn/JgGMRiKXj95Jq6RCurSzWnY7kZ1Pj4vQDobuGGcym3+L2lXMl73b7i3cZ6uJxWa5zyEl30BwEfFZr4J5Vb7k4D3FfMvYEiYf1G25i5IbC6pLVNFLC+DOLmcB7cYg+1ZVfV0rbyEux47pkMe6oqxvPcXyP0DGk=,iv:S7Bky2A+eiDwGy/m8cY0h1UUktOHjqX+QIha6cf+o5M=,tag:XtKC5+O1qj0uUbnAQ1D9AQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
