---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/name: &app emqx
    app.kubernetes.io/instance: *app
    app.kubernetes.io/part-of: *app
  name: *app
spec:
  hostnames:
    - emqx.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    # ── Root dash ───────────────────────────────
  - matches:
    - path:
        type: PathPrefix
        value: /

    backendRefs:
    - name: emqx-dashboard
      kind: Service
      port: 18083
      weight: 1

  # ── MQTT (WebSocket / MQTT over WebSocket) ─────────────────
  - matches:
    - path:
        type: PathPrefix
        value: /mqtt

    backendRefs:
    - name: emqx-listeners
      kind: Service
      port: 8084
      weight: 1