---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/name: &app emqx
    app.kubernetes.io/instance: *app
    app.kubernetes.io/part-of: *app
  name: *app
spec:
  hostnames:
    - emqx.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
      - kind: Service
        name: emqx-dashboard
        port: 18083
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
      - kind: Service
        name: emqx-listeners
        port: 8084
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /mqtt