apiVersion: v1
kind: Secret
metadata:
  name: emqx-secret
  namespace: home
stringData:
  EMQX_DASHBOARD__DEFAULT_USERNAME: ENC[AES256_GCM,data:Ga52J/BjgLsA,iv:2R+WaAsgw01/jgDnEIu8iJEaoIkNDy8D+y2dHXoyzog=,tag:t4dNsttOWMYucv0g3jiTsg==,type:str]
  EMQX_DASHBOARD__DEFAULT_PASSWORD: ENC[AES256_GCM,data:wVKA6RrMxBgW1N2Ggy4nTEdxvpVuFATAPds=,iv:ZRKOC4qSCAdl3paO64Zgv9E1KdBxn0eAII7CT2SZS9g=,tag:QrF/w4R++G1T92688yVbeg==,type:str]
  X_EMQX_APIKEY_KEY: ENC[AES256_GCM,data:ipd9p1xBDXynro7VCSsw7Z7xQ3WlFvr6RRjHZlZn+bnGEsMFw8LUJTfpmA==,iv:bGZMVR3TLCKPl+PTiNSLGCGiP/oPtaVG0ntBy/G83NY=,tag:VXrQw4dBIms6q2zzo02tQw==,type:str]
  X_EMQX_APIKEY_SECRET: ENC[AES256_GCM,data:GQIUnJqE8KWTx3nUSivC1hMsZQDI4TR/IfK2pSmQWStEbHeiF2m3CJI332JDZHEQ6ejXViGs89Pvq6t8ZM0hU2yNdNwc2nJxapAKjDrAB/Y5nOZFwNc=,iv:FXEcDlrm3SrQGDsrah+UtRdnIf2eetVflIzEhrDRevo=,tag:JYE0xudvijwfsjoj6ivAfQ==,type:str]
  X_EMQX_USERNAME_FRIGATE: ENC[AES256_GCM,data:zRPE2AQsjlrltjwaOv65M9AhgwNxyJ9wjjk=,iv:JM+QIwmz21BlaolwohTxJ1SOul2PWRDtBE9ocLua5ME=,tag:w+LETSXOR9HjM5miJPk6ug==,type:str]
  X_EMQX_PASSWORD_FRIGATE: ENC[AES256_GCM,data:jxfAjBB0GvDbTCvnyXizfj3NBb/8P6Lgb5k=,iv:o56+fIBIHuRQE99N9Q93XwhfFyc2hXyHrBxt5XqmFYs=,tag:5427VNtUpB5B3+QBeI3E/w==,type:str]
  X_EMQX_USERNAME_HOMEASSISTANT: ENC[AES256_GCM,data:S9iG34Api0JVm3YS,iv:Qow0z1KU9/o+YOGXqMGvT5oqBMOxVZfzmuj6P5d20uk=,tag:5or46LoLjiul7aHU0SYSNA==,type:str]
  X_EMQX_PASSWORD_HOMEASSISTANT: ENC[AES256_GCM,data:BYnnADeBIDC+tFhswAAaEo4w+ZxNjJKnTxk=,iv:HmpA+3DFVGDtbWWpUIOfpx/uC4VemtToH5I2fLuCIDs=,tag:9C1kZmktdId7npHQpLufjw==,type:str]
  X_EMQX_USERNAME_ESPRESENSE: ENC[AES256_GCM,data:5/+9uaejNs9bzOw=,iv:K7uvdsHUmk19cv2EiAOtyQP2gH5pK+d4VnvPYQ6qGrY=,tag:37VqUa9CrcHtmVPnspeXFA==,type:str]
  X_EMQX_PASSWORD_ESPRESENSE: ENC[AES256_GCM,data:1E6HuOOaKUf0z0C0eI2nX+a5IktHJwNhhrI=,iv:1q8qBzV6FathYTsMvz009XyjHJIhcsXZTb2Sxqg4kyk=,tag:Oj9iCnd738SZOimKeqBTKQ==,type:str]
sops:
  age:
    - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZnp0QWxzcHBlNW44MnZ1
        UnoyNFNlcjF5em1vbGR4eHdYUDhiMjVrdEg4CmxxTDh3dDNsWUdyVFg4d0MxUXlt
        T2tRRmhJeEpEV3pCbkpmUXY5d2lUbEUKLS0tIGN5ZUdqaXU3dFVoSzNyMm5GckNn
        RS9zYllSelpNdFJZNnh5QnRFOVZhVjQKWF6euT38uPPxiZdNv+jRXafN8hmy7jAK
        1BcfdUy+7GSig1yAEKdSR2vcuCjpB2BYOjL+rrn2VmERzKbkRd5xvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-15T21:48:05Z"
  mac: ENC[AES256_GCM,data:suzXQm96nUYzCfyBH83V00BtEdNfRC3dWvE62ENfJWrz3I8qYt26/NS3IbveXRbYu+69V4Lgy38uAGLvyJWgMf1cwwghZHA/rjqVjHZeLNb4T8R7up/03+dDhwKLg9TqCbbhuOL9C2qmDfYBgiGzWlbm+MKxr6uQL5GTToVNZsM=,iv:rraoufHz4pI+UGDM/QpFZ9VII4NUGnpfudj75DQLbHw=,tag:sdlVSpJjtvJGlhypfdYBFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
