apiVersion: v1
kind: Secret
metadata:
    name: synapse-secret
stringData:
    POSTGRES_SYNAPSE_PASSWORD: ENC[AES256_GCM,data:KLOo8XLwAppWWOkncnnxfTeSZP8whAh8QM02IOGp5VpYHPU=,iv:DWposncT7WSbGfkk0PE0KDvETEwrpECoezHaASFd4bs=,tag:3KHMeAJcL4vZW6iMcdHCsA==,type:str]
    redis-password: ENC[AES256_GCM,data:n8znMd6LHVndEVZUhUFMEEXHirXH9qY=,iv:iS7aIuDfCh6cv/AcOX/7L6i2k0jX38wHpVBWOdiyVcI=,tag:t3rBWcKfw7seL7PHbIRglw==,type:str]
sops:
    age:
        - recipient: age1zpu6nk55vkwm2ukyq2v2gfke9qkmhh2psn3phvw8uauzxhvfcdtq75vlep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMclBYNndlRUs1ZVVpYjli
            bGVRN2ptaG0zK2dQUlk4R0Y0V1VCbDl2akRBCkZRditmNndtdzE1SXFuMThGTHZW
            VFhKS1RYekZsV3A0ZzIyellqM0xMQ0UKLS0tIHFlOXh3Y0pUeG93RUQxeG5lL0RI
            Q0d6L0JHVEFNbDJJYWVTYmNCL2VRelUK9qMwN5leVWVBo5Z90TLZXWHzyvvsofK6
            exYANCGCAngy+AMQr9QJGR2hpMvdjiTG3+igYBno9P2EJobsp3TTYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T23:48:57Z"
    mac: ENC[AES256_GCM,data:2OAkAhua3/lF+7SsICE/Y0XzD1FeF5z1sIqN+8n/C5Me4dEikzjY/gYL1AG7H0tlPnMU3oWRYKHWvErMiQcB1Vi4HeCR7EwTvp5HxM4Tl1WbcP+kaiJkjeOmwHerU0p57OrKPcSoRJ/7wddYhsVqKcxlg07fBWsiZ/Oy70erPek=,iv:FSG4gwP0GHD67QktuNpRBZSyiStCA0Et9rEkHzxDgDM=,tag:34ohLFNg65yfaeex/obKaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
